name: schema_evolution
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pyspark~=3.3.0
  - pandas~=1.3.2
  - boto3~=1.36.3
  - awswrangler~=3.11.0
  - faker~=30.8.1
  - pip
  - pip:
    - -e .
    # - pytest
    # - black
    # - flake8
    # - pytest-spark
    # - pytest-cov